# Generated by Django 2.0.13 on 2019-05-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_word', models.CharField(max_length=200)),
            ],
        ),
    ]
